name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar as dependencias
        run: npm install

      - name: Rodar os testes
        run: npx jest